"""create_documents

Revision ID: 7179db6a526e
Revises:
Create Date: 2026-07-01 14:36:16.197607

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7179db6a526e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("rubrics", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column(
            "created_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_documents_created_date",
        "documents",
        [sa.literal_column("created_date DESC")],
        unique=False,
    )
    op.create_index(op.f("ix_documents_id"), "documents", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_documents_id"), table_name="documents")
    op.drop_index("idx_documents_created_date", table_name="documents")
    op.drop_table("documents")
    # ### end Alembic commands ###
